# Generated by Django 3.2.7 on 2021-10-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentTracker', '0005_alter_assessments_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessments',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
