# Generated by Django 3.2.7 on 2021-10-09 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentTracker', '0006_alter_assessments_title'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assessments',
            table='Assessments',
        ),
    ]
