# Generated by Django 3.2.7 on 2021-10-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessmentTracker', '0010_auto_20211009_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessments',
            name='state',
            field=models.CharField(default='halfway', max_length=50),
        ),
    ]
